### ISSUE TITLE
add an effect on student login page ...

### ISSUE THREAD

**Issue by Akashkumar9508** [Akashkumar9508/Smart-Attend#15]
Bicky sharm you have to do it  **### _when the teacher click on their teacher id section to login , the palceholder translate to top_**
### And remodify it , like teacher login page

**Comment by bickysharma519** [comment]
> Bicky sharm you have to do it **### _when the teacher click on their teacher id section to login , the palceholder translate to top_**
> 
> ### And remodify it , like teacher login page

already remodified like teacher login page and pull request is also given you need to approve it
